# Generated by Django 3.2.8 on 2021-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211103_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('Order Recieved', 'Order Recieved'), ('Order Complete', 'Order Complete'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing')], default='Order Recieved', max_length=30),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
